### ISSUE TITLE
To merge or not to merge with the umbrella repo?

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renga-documentation#9]
I would propose to move the documentation under `/docs` in the main Renga repo.

## Pros
- easier tagging when a release is made
- "always" in sync with latest development

## Cons
- longer travis builds

--
cc @rokroskar @erbou

**Comment by rokroskar** [comment]
incidentally, we discussed this at the end of today's meeting -- I think it's a good idea, especially if we could have a way of automatically pulling in documentation from the other components.

**Comment by jirikuncar** [comment]
Yes, we can use intersphinx.
